### PR TITLE
Logo pull request

### PR DESCRIPTION
**Pull request by memoryskull**
I hope you guys liked the job.

This is just to have a proof of the collaboration we just created.

Thanks for letting me be a part of this project!

Soon i'll be uploading a google drive where all the formats of the logo would be available for you guys to download if its of any use!

### CODE REVIEW

**Comment by memoryskull** [comment]
Hi @rashadg1030 
Because he has not accepted the pr if he meets all the conditions?

**Comment by memoryskull** [comment]
Hi @rashadg1030
Because he has not accepted the pr if he meets all the conditions?

**Comment by memoryskull** [comment]
Hello @rashadg1030 
What is the problem with the pr

**Comment by rashadg1030** [comment]
Thank you for your contribution👍🏽

**Pull request merged**
